highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://hsemarap.github.io/resume
author: Fábio Madeira

# edit this section with your information
# hsemarap.github.io - all contents run on /resume/
# for a normal use at the base of the server change it to "/"
baseurl: /resume/
title: Parameswaran D's Resume
name: Parameswaran Desigavinayagam
email: parameshone@gmail.com
email_full: mailto:parameshone@gmail.com
website: hsemarap.github.io/
website_full: https://hsemarap.github.io/
github: hsemarap
twitter: hsemarap
tel: +1 646 624 9286
tel_full: tel:+1646249286
google_maps: ''
address:
  street: 
  postcode: 
  city: West Lafayette, IN
  country: United States
google_analytics:

# needed for travis-ci build
exclude: [vendor]
includes:
- resume/_includes
- resume/_layouts
- resume/_site
